CFLAGS = -Wall -Og

all: EJ1.bin, EJ2.bin EJ3.bin, EJ4.bin, EJ5.bin

EJ1.bin:
	g++ $(CFLAGS) -o EJ1.bin .cpp

EJ2.bin:
	g++ $(CFLAGS) -o EJ2.bin .cpp

EJ3.bin:
	g++ $(CFLAGS) -o EJ3.bin P4_EJ3_MarcoGirelaVida.cpp

EJ4.bin:
	g++ $(CFLAGS) -o EJ4.bin .cpp

EJ5.bin:
	g++ $(CFLAGS) -o EJ5.bin .cpp

clean:
	rm -f EJ1.bin EJ2.bin EJ3.bin EJ4.bin EJ5.bin