HOME = .
INCLUDE = $(HOME)
SRC = $(HOME)
BIN = $(HOME)
OBJ = $(HOME)
CFLAGS = 

all: red_conexiones algoritmoMesaRedonda rutaAutobus algoritmoParejas algoritmoAsfaltarCalles

red_conexiones:
	g++ $(CFLAGS) -o $(BIN)/red_conexiones $(SRC)/red_conexiones.cpp

algoritmoMesaRedonda:
	g++ $(CFLAGS) -o $(BIN)/algoritmoMesaRedonda $(SRC)/algoritmoMesaRedonda.cpp

rutaAutobus:
	g++ $(CFLAGS) -o $(BIN)/rutasAutobus $(SRC)/rutasAutobus.cpp

algoritmoParejas:
	g++ $(CFLAGS) -o $(BIN)/algoritmoParejas $(SRC)/algoritmoParejas.cpp

algoritmoAsfaltarCalles:
	g++ $(CFLAGS) -o $(BIN)/algoritmoAsfaltarCalles $(SRC)/algoritmoAsfaltarCalles.cpp